### ISSUE TITLE
[20210603 ~ ]유튜버 경돼 문제해결 방안 모색

### ISSUE THREAD

**Issue by DominKim** [DominKim/Data_literacy#11]
## 유튜브 콘텐츠의 제작·이용 환경 특성과 인기 채널 분석 및 함의점 고찰
- 성공요인
  - 독창적 콘텐츠 기획(O)
    - 경돼만의 아이덴티티가 담긴 Vlog
  - 간결하고 잘 전달되는 내용 편집(△)
    -  주로 10분 이내의 짧은 영상들이지만 명확한 주제가 아닌 영상들은 어떤걸 전달하려는지 알 수 없다.
  - 지속적인 운영 관리(X)
    - 다시 시작
  - 소통으로 시청자들과 신뢰 관계를 형성하는 것
    - 오카방, SNS를 이용하고 있지만 편향된 소통을 하고 있음

- 솔루션
  1) 기존 Vlog 형식의 영상을 꾸준히 올리기(Upload 횟수가 조회수에 큰영향이 없기 때문에 많이 올릴 필요가 없음, 주 1회)
     - 18년도의 컨텐츠 형식 참고 필요!
  2) 라이브 방송을 통한 소통 or 영상 대댓글을 통한 소통
  3) Pick video topics with the help of keyword research(제목, 개요 키워드에 추가 방법)
    - 운동 : 브이로그, 자극
    - 직장인 운동 : 브이로그, 루틴, 식단, 루틴
    - 경돼 : 다이어트, 벤치프레스, 스쿼트, 3대

**Comment by dodorip** [comment]
문제점 분석

유의미한 변수 1 : upload_count 
유의미한 변수 2 : interest_rate
    
시청수 떨어진 이유 : "upload_count" / 메인 영상 컨텐츠수 감소(시간, 내용)
> 아직 구독 및 경돼님 영상을 주시하고 있는 시청자들은 여전히 나쁘지 않은 흥미도를 갖으며 경돼님의 "제대로된" 영상이 올라오면 시청하고 있음.(최근까지도)
>그러나, 경돼님의 업로드 횟수에 비례하여 조회수는 감소하고 있다.
>또한, 최근 영상이 올라오더라도 경돼님의 시청자들이 선호하는 일상 + 운동 (10분정도)되는 영상이 올라오지 않는다. 
**경돼님이 유튜브 업로드에 중점을 두어 양질의 영상을 올리지 못하신다.**
이는 영상을 올리더라도 큰 의미가 없을 수 있다.

느낀점: 2017~2018년도에 큰 폭으로 상승하였고 이후 다시 감소하였다. 그러나 이는 2018년도가 구독자 최고를 찍은 시점이며 실질적으로 활동하는 구독자가 많았다. 따라서, 시간이 지남에 따라 감소하는 것은 자연스럽다고 생각된다.(17,19 평균 조회수 비슷)
또한, 2018년도에는 경돼님의 메인 컨텐츠(일상+운동)이외에도 신규 시청자들을 끌어들일"다양한 컨텐츠"들을 많이 했고 이는 유효한 결과를 도출했다. 
1)유행에 따른 영상이 제작되었으며(펑티모, 언더아머 등),
2)알고리즘의 영향을 받은 영상들도 많이 제작하였다.(유도, 주짓수)
2018년도에는 특정 헬스 유튜버의 팬층이 존재하지 않으며 다양한 헬스에 관심있는 시청자들이 다양한 헬스 유튜버들의 영상을 시청하였으며 경돼님도 이에 해당한다. 그러나 18년도 이후 많은 헬스 유튜버들이 높은 수의 독자적인 구독자들을 보유하고 있다.

**Comment by MoonSeongIl** [comment]
데이터 분석
1. 조회수
1) 2016 ~ 2018년 : 약 20~30만 조회수
2) 2019 ~ 2020년 : 약 71만, 19만 조회수
조회수가 많이 떨어진 것으로 확인된다.
상관 분석을 한 결과 조회수와 관심도(좋아요, 싫어요, 댓글 수의 합)가 0.84로 아주 높은 결과를 보여주었습니다.
관심도에 관련있는 변수는 당연히 영상을 보신 분들이기 때문에 상관 관계가 높다고 생각할 수 있습니다.

2. 업로드 수
1) 2016 ~ 2018년 : 1800~3000 회 업로드 수
2) 2019 ~ 2020년 : 640, 120회 업로드 수
업로드 수가 많이 떨어진 것으로 확인된다.
상관분석을 한 결과 업로드 수와 조회 수 간의 관계가 없다고 생각했으나,
연도 별로 관계를 파악한 결과 상관관계가 높은 것으로 확인된다.(분석 결과로 보여줄 예정)

-- 토요일까지 더욱 업로드 할 예정.
