### ISSUE TITLE
[20210501~20210508]유튜브 관련 사전조사

### ISSUE THREAD

**Issue by DominKim** [DominKim/Data_literacy#2]

**Comment by jyeon94** [comment]
https://ordinius.tistory.com/374
유튜브 수익 구조에 대한 간단한 정보입니다.
경돼님의 정확한 니즈가 어떤것일지는 아직 구체적이지 않으나 보통 유튜버라면 수익 증대가 목표라 생각하여 가져왔습니다.

**Comment by DominKim** [comment]
유튜브 콘텐츠의 제작·이용 환경 특성과 인기 채널 분석 및 함의점 고찰
http://www.riss.kr.libproxy.dankook.ac.kr/search/detail/DetailView.do?p_mat_type=1a0202e37d52c72d&control_no=0b10c47201eb3cb0d18150b21a227875

국문초록(결론부분)
분석으로 도출된 유튜브 채널 성장 법칙은 첫째, 독창적 콘텐츠 기획, 둘째, 간결하고 잘 전달되는 내용 편집, 셋째, 지속적인 운영 관리, 넷째, 소통으로 시청자들과 신뢰 관계를 형성하는 것이다. 유튜브의 이러한 특성들로 현재 전 세계적으로 유튜버, 크리에이터, 콘텐츠 업로더 혹은 인플루언서라는 새로운 직업 영역을 창출하고 있다

**Comment by DominKim** [comment]
목적 및 문제 정의
- 포인트 1 : 사용된 언어가 구체적이고 명확한가?
- 포인트 2 : ‘문제’, ‘원인’, ‘해결 방안’을 구분하고 있는가?
  > 작업을 시작하기 전에(본격적인 분석), 해결하고자 하는 ‘문제’와 그 ‘목적’에 대해 명확히 할 필요가 있다.(우리는 인터뷰를 통해 실시)
  > 시작도 하기 전에 주관적인 자시의 추측을가지고 원인을 단정짓는 것은 바람직하지 않다.(객관적이고 논리적)

**Comment by jyeon94** [comment]
**데이터 문해력 chapter 1.**

데이터 작업의 3단계

1. 문제 및 목적을 정의하고 가설을 구축
2. 분석을 위한 기술과 지식 활용 (기계와 도구가 더 잘하는 부분)
3. 분석결과에 대한 해석 및 스토리 구축
    => 목적과 문제에 따른 해석 추가 (스토리)

1번과 3번이 데이터 문해력이 필요한 부분

**목적사고력**: 데이터 작업 전에, 무엇이 알고 싶은지 생각 후 이에 필요한 데이터를 활용해 작업을 진행하는 접근 방식
                         => '내가 이 데이터를 통해 무엇을 알고 싶은지', '이를 알게되면 무엇을 하고 싶은지', '이를 위해서는 어떤(지표)가
                                필요한지

**목적/문제 정의, 현상파악, 평가 요인 방법 **
1. 겉으로 드러난 현상 파악
2. 목적 및 문제를 정의
3. 지표를 결정
4. 현재 상태를 파악
5. 평가
6. 요인을 분석
7. 해결방안을 모색
