### ISSUE TITLE
[20210509~ ] 경돼 인터뷰 내용 정리

### ISSUE THREAD

**Issue by fyiusuck** [DominKim/Data_literacy#4]
미팅 노트 정리 및 공유

**Comment by fyiusuck** [comment]
린캔버스 참조해서 작성

**Comment by jyeon94** [comment]
1. 문제
   - 영상 퀄리티의 저하, 영상 길이 감소, 업로드 횟수 감소로 인한 구독자 이탈
   
2. 고객군
   - 성장에 대해 관심있는 시청자
   - 일반 구독자가 아닌 충성 구독자를 유입시키는 것이 목표
      => 현재 지속적으로 영상 시청하는 구독자 대략 2000명
   
3. 고유의 가치제안
   - 일반인인 자신이 성장하는 모습을 보여주면서 영상을 보는 시청자도 자신처럼 성장할 수 있다는 의지 부여
   - 어그로성의 영상이 아닌 진정성 있는 영상을 제작하려고 노력

4. 솔루션
   - 경돼님의 솔루션:
      1. 5월 중순 부터 편집가 계약을 통해 영상 퀄리티 향상
      2. 6월말 부터 다이어트 돌입하여 영상 촬영
    - 데이터 리터러시 솔루션:
       1. 썸네일, 제목등의 변화를 주어 A/B 테스트를 통해 효과 측정
       2. 중요 지표에 대한 결정 필요 

5. 채널
     - 유튜브, 인스타그램, 페이스북, 오픈 카카오톡

6. 수익원 
      - 회사 월급, 유튜브 수익, 협찬, 광고(예전 언더아머,프로틴)

7. 비용 구조:
    - 영상 촬영에 필요한 카메라, 노트북(?) 
    -  추후에 편집자 고용시 편집자 비용
    -   도민님이 언급했던것 처럼 간접적 비용인 **시간**
         - 현재 일, 앱 개발, 운동, 유튜브등 시간 투자하는 곳이 많아 가장 중요한 비용 중 하나라고 판단됨

8. 핵심 지표:
     - Retention(유지): 충성 구독자인 2000명이 이탈하지 않고 지속적으로 영상 시청하는지 측정 필요
     - Bounce Rate(이탈률): 구독자가 이탈한 시점 측정, 영상 어느 부분에서 시청을 그만 하는지등 경돼님이 전달 주는 데이터로 파악 필요
     - Conversion Rate(전환률): 구독하지 않고 보는 사람이 구독하는 시점이 언제인지 측정 필요 또는 구독자가 증가한 영상의 원인 파악 필요

9. 경쟁우위:
      -

**Comment by MoonSeongIl** [comment]
1. 문제

관심이 줄어드는 시청자.
다양한 고객군이 형성되지 않는 충성도가 높은 고객 2000명. 2000명 이상이 증가되기가 쉽지 않음.

2. 고객군

1. 한 사람의 성장에 관심있는 구독자.
2. 헬스에 진정성있는 자세로 임하는 자.

3. 고유의 가치제안
기존에 유명하고 인기있는 유튜버와는 다른 재미, 인플루언서 합방보다는 일반인의 입장에서 성장하는 모습을 보여주는 채널.

4. 솔루션
기존에 촬영, 편집을 본인이 했다면, 편집자 채용 예정
다양한 유튜버들과 합방 예정

5. 채널
유튜브 영상
인스타그램 story

6. 수익원
영상 조회 수와 관련하여 직접적으로 발생.
인스타그램 홍보(언더아머) 등.

7. 비용구조
영상 편집 툴, 카메라, 헬스장 사용비
촬영, 편집 시간

8. 핵심지표
영상 조회수, 구독자수라는 정량적인 KPI 도출.
사람들의 관심을 알 수 있는 헬스 커뮤니티에 언급 횟수 등

9. 경쟁 우위
자신의 생활을 솔직하게 영상에 나타내는 모습.
직장인이라는 타이틀과 요즘 사람들이 관심이 많은 헬스라는 좋은 매개체를 가지고 있음.(사람들의 관심이 이목될 수 있는)

 
Retention(고객 유지) : 고객이 회사의 제품을 계속해서 이용하는 것.
(고객이 계속해서 우리가 원하는 행동을 하는가)


충성도가 높은 구독자(2000명) 시청 지속 시간(유튜브)

인트로 : 동영상 초반부 30초 후에도 시청을 지속한 시청자의 비율을 나타냅니다.
높은 인트로 비율 : 
동영상 초반 30초의 콘텐츠가 동영상 썸네일 및 제목을 보고 시청자가 기대한 것과 일치합니다.
콘텐츠에 대한 시청자의 관심이 유지됩니다.

연속 세그먼트 : 동영상에서 이탈한 시청자가 거의 없는 구간.

급상승 구간 : 동영상에서 시청자가 반복 시청하거나 건너뛰기로 재생한 구간.

하락 구간 : 동영상에서 시청자가 건너뛰거나 시청을 완전히 중단한 구간을 강조 표시

참고: 동영상에 네 가지 구간이 모두 존재하지 않을 수도 있으며, 동영상 내에서 감지된 구간만 강조표시됩니다. 동영상 길이는 60초 이상이고 조회수가 100회 이상이어야 합니다.

충성도가 높은 구독자가 위와 같은 4개의 지표에서 어떠한 형태로 보이고 있는지 확인하면 좋을 것 같고, 일반 시청자들도 보면 좋을 것 같습니다.

**Comment by fyiusuck** [comment]
customer segments
운동에 관심있는 20~30대 남자 직장인
자기관리에 관심있는 20~30대 남자 직장인

문제
많은 현대인들이 직장을 다니며 자기관리를 병행하는 것을 어려워함
특정 연령대(경돼 구독자 20중반~30중반 남성 추정)에 들어서면 본인만의 라이프스타일에 대한 정립 욕구 있으나 마땅히 조언받을 만한 곳이 없음
운동에 대한 조언 듣고싶어함

가치제안
운동을 꾸준히 하는 직장인의 라이프스타일에 대한 디테일한 이야기를 들을 수 있음
크리에이터의 성장을 관찰할 수 있음(남의 일기 훔쳐보기)

솔루션
운동과 라이프스타일(브이로그)을 같이 보여주는 유튜브 콘텐츠 제작 통해 조언 제시
일을 병행하며 변화하는 모습, 성장하는 모습의 콘텐츠 제작 통해 동기부여 및 조언 제시

기존 대안
운동과 브이로그를 같이 찍는 유명 유튜버들(말왕, 지피티, 운지기 등)
운동 비중이 많음

채널(시청자 유입 경로)
동영상 추천(킹고리즘)에 의한 유입
Long(썸네일, 제목, 태그, info)
#Shorts(제목, 태그, info)
직접 검색
연관 동영상 통한 유입
외부 사이트 통한 유입 등

cost structure
영상 촬영에 쏟는 노력
콘텐츠 촬영 자체에 투입되는 시간
영상 편집에 쏟는 노력
편집자 비용
본인 투입 비용

revenue streams
기간별 구독자 수 증가량
기간별 조회수 증가량

Key Metric(viewer 확보를 위한)
경돼 동영상에의 첫 방문(acqusition단계) - 동영상별 시청지속시간
썸네일 및 제목, 태그 임팩트 필요
유입 시청자가 원하던 콘텐츠와의 정확한 일치(activation 단계) - 댓글
그래 직장인이 이런 점이 힘들지(공감) -> 댓글로 이어져야함
아 이렇게 하면 되겠구나(조언) -> 그럼 이럴땐 어떻게 하지? -> 질문이 댓글로 이어져야함 -> 댓글 & 커뮤니티탭 통한 의사소통 진행
이 사람 대단하다. 존경스럽다. -> 댓글로 이어져야함
단순한 재미(retention관점) - 나중에 볼 동영상 추가 & 구독
캐릭터에 대한 기대감(아 이 사람 다음 동영상 궁금하다)
아 이 사람 다음 동영상 궁금하다
어떻게 변화되었을까?
동영상 페이지에서 구독이 바로 이어져야함

일방적 경쟁우위(Unfair advantage)
이부분은 린캔버스(블루오션)라서 쓰는데 BM캔버스(레드오션)이면 안쓰는 부분이라고 함. 근데 경쟁우위 정립 잘 못하겠음

**Comment by fyiusuck** [comment]
customer segments
- 운동에 관심있는 20~30대 남자 직장인
- 자기관리에 관심있는 20~30대 남자 직장인

문제
- 많은 현대인들이 직장을 다니며 자기관리를 병행하는 것을 어려워함
- 특정 연령대(경돼 구독자 20중반~30중반 남성 추정)에 들어서면 본인만의 라이프스타일에 대한 정립 욕구 있으나 마땅히 조언받을 만한 곳이 없음
- 운동에 대한 조언 듣고싶어함

가치제안
- 운동을 꾸준히 하는 직장인의 라이프스타일에 대한 디테일한 이야기를 들을 수 있음
- 크리에이터의 성장을 관찰할 수 있음(남의 일기 훔쳐보기)

솔루션
- 운동과 라이프스타일(브이로그)을 같이 보여주는 유튜브 콘텐츠 제작 통해 조언 제시
- 일을 병행하며 변화하는 모습, 성장하는 모습의 콘텐츠 제작 통해 동기부여 및 조언 제시

기존 대안
- 운동과 브이로그를 같이 찍는 유명 유튜버들(말왕, 지피티, 운지기 등)
- 운동 비중이 많음

채널(시청자 유입 경로)
- 동영상 추천(킹고리즘)에 의한 유입
	- Long(썸네일, 제목, 태그, info)
	- #Shorts(제목, 태그, info)
- 직접 검색
- 연관 동영상 통한 유입
- 외부 사이트 통한 유입 등

cost structure
- 영상 촬영에 쏟는 노력
	- 콘텐츠 촬영 자체에 투입되는 시간
- 영상 편집에 쏟는 노력
	- 편집자 비용
	- 본인 투입 비용

revenue streams
- 기간별 구독자 수 증가량
- 기간별 조회수 증가량

Key Metric(viewer 확보를 위한)
- 경돼 동영상에의 첫 방문(acqusition단계) - 동영상별 시청지속시간
	- 썸네일 및 제목, 태그 임팩트 필요
- 유입 시청자가 원하던 콘텐츠와의 정확한 일치(activation 단계) - 댓글
	- 그래 직장인이 이런 점이 힘들지(공감) -> 댓글로 이어져야함
	- 아 이렇게 하면 되겠구나(조언) -> 그럼 이럴땐 어떻게 하지? -> 질문이 댓글로 이어져야함 -> 댓글 & 커뮤니티탭 통한 의사소통 진행
	- 이 사람 대단하다. 존경스럽다. -> 댓글로 이어져야함
- 단순한 재미(retention 관점) - 나중에 볼 동영상 추가 & 구독
	- 캐릭터에 대한 기대감(아 이 사람 다음 동영상 궁금하다)
	- 아 이 사람 다음 동영상 궁금하다
	- 어떻게 변화되었을까?
	- 동영상 페이지에서 구독이 바로 이어져야함

일방적 경쟁우위(Unfair advantage)
- 이부분은 린캔버스(블루오션)라서 쓰는데 BM캔버스(레드오션)이면 안쓰는 부분이라고 함. 근데 경쟁우위 정립 잘 못하겠음

**Comment by DominKim** [comment]
문제? 사람들이 불편함을 느끼는 진짜 문제점을 찾았는가?(경돼의 의견이 중요하다! < 구독자의 의견이 중요하다!)

  - 영상의 길이, 퀄리티, 횟수에 따른 구독자 수 이탈(실험이나 기존 연구자료를 통해 확인 필요!)
    - 인터뷰를 통해 경돼가 직관적인 수치를 보고 확인 하였지만 크롤링을 통한 데이터 수집으로 정량화 필요

  - 컨텐츠 변화로 인한 구독자수 이탈(구독자 인터뷰 필요!, 지인 한명을 인터뷰 했을 시 나왔던 문제점)
    - 기존 구독자에 의하면 직장인 컨텐츠로 변하면서 시청 횟수가 줄어둠
    - 대학생 > 직장인

2. 고객군? 목표 시장을 알고 있는가? 고객군을 구별해서 각각에 맞는 메시지를 전달할 방법을 알고 있는가?(유튜브 스튜디오 통해서 직접 확인!)
  - 기존 경돼 유뷰트를 꾸준히 시청하는 남성 약 2000천여명의 구독자(확인이 필요하다!)
    - 만 18 ~ 24세 : 34%, 만 25 ~ 34세 : 43%(사진 참고)
    - '성장'에 초점을 맞춘 컨텐츠를 제작해 왔지만 과연 기존 구독자들이 어떠한 니즈(일상, 학교생활 등)가 있는지 파악할 필요가 있다.
    - 유튜브 스튜디오를 통해서 확인한다.(예) 유입경로, 시청 디바이스, 내 시청자가 시청하는 다른 채널 and 동영상, 순 시청자 수 등) 
    - How? 유튜브 스튜디오 -> 분석 -> 시청자층에서 확인

3. 고유의 가치 제안? 여러분의 제품이 왜 더나은지 또는 어떻게 다른지 명료하고 독특하며 기억에 남는 방법으로 설명할 수 있는가?(‘경돼’의 정의가 제일 필요! )
  - 기존 헬스 유튜버와는 다른 '성장'에 맞춘 일상생활 운동 v-log 채널

4. 솔루션? 문제를 적절한 방식으로 해결할 수 있는가?
  - 영상 퀄리티를 늘리기 위해 편집자 채용예정
    - A/B Test등을 통해 이러한 방식이 효과적인 파악 필요(경돼가 적용 했을 시 데이터로 검증!)

5. 채널? 고객에게 제품이나 서비스를 어떻게 전달하고 매출을 발생시킬 것인가?
  - 유튜브 영상, 인스타 업로드, 유명 유튜버 합방예정(유튜브 스튜디오를 해결)

6. 수익원? 수익이 어디에서 발생하는가? 일회성인가 반복적으로 발생하는가? 수익이 직접적으로 발생하는가 아니면 간접적으로 발생하는가?
  - 영상 시청 횟수를 통한 광고료로 간접적으로 발생
  - 협찬(마이프로틴, 닭가슴살 등)

7. 비용 구조? 사업 운영에 필요한 직 간접 비용은 무엇인가?
  - 영상 편집에 필요한 노트북, 영상 촬영할 카메라, 편집 툴
  - 편집자 급여(예정)
  - '시간'

8. 핵심 지표? 사업이 잘되고 있는지 알기 위해 어떤 숫자들을 추적해야 하는지 알고 있는가?
  - 이번 분석을 통해 KPI 도출이 필요함(경돼의 경우 시청횟수나 댓글을 중요하게 보고 있음)
  - 사용자 제작 콘텐츠 목표기준, 해적지표 중에 하나로 선정이 필요(Retention)

9. 경쟁우위? 여러분의 노력이 경쟁자보다 더 좋은 결과를 내도록 만드는 '증폭기'는 무엇인가?(‘경돼’의 의견, 구독자들이 구독을 하는 ‘이유')
  - 경돼의 경우 본인이 성장하기 위해 했던 여러가지 노력들을 영상을 통해 표출하는 것
    - 최근에는 성장동력을 잃어 버렸음

- 경돼의 경우는 기존 시청자들의 공감을 불러 일으키는 영상을 통해 유지를 하고 이를 기반으로 채널의 성장하기를 원함
  - 따라서, [Retention]을  유지하고 늘리는데 초점을 맞추는 것이 필요.
  - __Retention 지표를 정량화 하기 위한 방법__ 이 필요!!
  - 이러한 Retention을 유지하기 위해서는 결국에 컨텐츠가 가장 중요할 것이라고 판단.


제안사항 궁금한 점

제안사항
유튜브 라이브를 통해 구독자와 소통의 시간을 가졌으면 한다.
    - Why? 구독자들의 의견을 통해 현재 문제점을 파악하기 위해


궁금한 점
본인 채널의 본인만의 정의, 타 유튜버 대비 본인 채널의 장점(차별점)
구독자 수를 늘리는게 목표인지? or 실 구독자(2000명)를 늘리는게 목표인지?
유튜브를 통해 진짜로 수익 창출을 하고 싶은지?
제작하는 App과 유튜브랑 관련이 있는지?
