### ISSUE TITLE
[20210523 ~ ] 경돼 유튜브 Web Crawler 작성!

### ISSUE THREAD

**Issue by DominKim** [DominKim/Data_literacy#9]
1. 웹 크롤러 작성 시작
  - 20210527 : 웹 크롤러 피드백

2.

**Comment by fyiusuck** [comment]
api 있길래 예문보고 테스트.
셀레니움 구동 테스트 예정.

**Comment by DominKim** [comment]
https://github.com/minyong-shin/Bloging/blob/master/MY%20-%20유튜브%20info%20및%20댓글%20크롤링.ipynb

**Comment by fyiusuck** [comment]
> api 있길래 예문보고 테스트.
> 셀레니움 구동 테스트 예정.

https://google-api-client-libraries.appspot.com/documentation/youtube/v3/python/latest/

**Comment by fyiusuck** [comment]
김윤수 크롤러 작성 실습중~

**Comment by MoonSeongIl** [comment]
문성일 웹 크롤러 작성 실습 중, 다만 아직 많이는 하지못했습니다! 빠르게 해 나가겠습니다~

**Comment by DominKim** [comment]
~ 6.1(화) 완성
~ 6.4(금) 데이터로 문제점 파악

**Comment by DominKim** [comment]
경돼가 원하는 것은 Activation(구독)
- 영상의 마케팅 메시지과 유저 리뷰등에서 나오는 키워드와 일치하는지 확인!
